version: '3.4'
services:
  postgres:
    image: postgres:10
    volumes:
      - ./mnt/postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - local.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    env_file:
      - local.env
    ports:
      - 80:80