version: '3.7'

volumes:
  postgres_data: null
  object_storage: null

networks:
  algo_trading_network: null

services:
  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification
    env_file:
      - ./email_service/.env
    ports:
      - 8000:8000
    networks:
      - algo_trading_network

  backtest:
    build:
      context: .
      dockerfile: Dockerfile.backtest
    env_file:
      - ./back_testing/.env
    ports:
      - 8005:8005
    networks:
      - algo_trading_network

  postgres:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=price_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - algo_trading_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 80:80
    networks:
      - algo_trading_network

  redis:
    image: redis:6
    ports:
      - 6379:6379
    command: redis-server --requirepass redispassword
    networks:
      - algo_trading_network

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    volumes:
      - object_storage:/object_storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /object_storage --console-address ":9001"
    networks:
      - algo_trading_network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
